Fixup bad reference in borrow
error: cannot explicitly dereference within an implicitly-borrowing pattern
  --> src/bin/08.rs:72:31
   |
72 |             .filter(|((_, _), &c)| c.is_ascii_alphanumeric())
   |                               ^ reference pattern not allowed when implicitly borrowing
   |

2024 edition doesn't like that, and I can't say I blame it.

Simple fix here was to drop the attempt to deference, which was a
leftover from a previous edit where I was checking the value against
b'.' to filter out the non-antennas rather than using
is_ascii_alphanumeric to select the antennas.